[package]
name = "fungus"
version = "0.1.0"
edition = "2024"
description = "Optimizing Befunge interpreter"
repository = "https://github.com/krobbi/fungus"
license = "MIT"
keywords = ["befunge", "esolang", "interpreter"]
categories = ["command-line-utilities", "compilers"]
publish = false

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
rand = "0.9.2"
thiserror = "2.0.18"

[lints.rust]
unknown_lints = "forbid"

[lints.clippy]
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_const_for_fn = "allow"

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
